# CICD using GitHub Actions

name: CI/CD

# Exclude the workflow to run the changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'RBAC.md'

jobs:
  
  build: 
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        maven: [ '3.8.8' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven=${{ matrix.maven }}*
      
    - name: Build with Maven
      run: mvn package -DskipTests=true

  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-master-pro:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
    
    - name: Update tag in helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/taskmaster-chart/values.yml

    - name: Commit and push changes
      run: |
        git config --global user.email "goutham@gmail.com"
        git config --global user.name "goutham"
        git add helm/taskmaster-chart/values.yml
        git commit -m "Update tag in helm chart"
        git push